Repository cygnusb2b/informa-business-intelligence, pull requests merged in 2021-01, with the labels that each got.

#250 Upgrade @base-cms dependencies to 1.51.1
  packages/informa-gam/package.json
  packages/lazarus-shared/package.json
  packages/leaders/package.json
  sites/americanmachinist.com/package.json
  sites/asumag.com/package.json
  sites/bulktransporter.com/package.json
  sites/contractingbusiness.com/package.json
  sites/contractormag.com/package.json
  sites/ecmweb.com/package.json
  sites/ehstoday.com/package.json
  sites/electricalmarketing.com/package.json
  sites/electronicdesign.com/package.json
  sites/ewweb.com/package.json
  sites/fleetmaintenance.com/package.json
  sites/fleetowner.com/package.json
  sites/forgingmagazine.com/package.json
  sites/foundrymag.com/package.json
  sites/hpac.com/package.json
  sites/hydraulicspneumatics.com/package.json
  sites/industryweek.com/package.json
  sites/machinedesign.com/package.json
  sites/mhlnews.com/package.json
  sites/mwrf.com/package.json
  sites/newequipment.com/package.json
  sites/powerelectronics.com/package.json
  sites/refrigeratedtransporter.com/package.json
  sites/rermag.com/package.json
  sites/sourcetoday.com/package.json
  sites/tdworld.com/package.json
  sites/trailer-bodybuilders.com/package.json
  sites/trucker.com/package.json
  sites/truckfleetmro.com/package.json
  yarn.lock
Labels: dependencies

#251 Remove two items from Trucker nav
  sites/trucker.com/config/navigation.js
Labels: 🌐 site: trucker.com

#252 Include metatags in Company & “full-width” content overrides
  packages/lazarus-shared/templates/content/company.marko
  packages/lazarus-shared/templates/content/full-width.marko
Labels: 🌐 site: ALL

#253 Update navigations
  sites/bulktransporter.com/config/navigation.js
  sites/mwrf.com/config/navigation.js
  sites/refrigeratedtransporter.com/config/navigation.js
  sites/tdworld.com/config/navigation.js
  sites/trailer-bodybuilders.com/config/navigation.js
Labels: 🌐 site: bulktransporter.com, 🌐 site: mwrf.com, 🌐 site: refrigeratedtransporter.com, 🌐 site: tdworld.com, 🌐 site: trailer-bodybuilders.com

#254 Upgrade @base-cms dependencies to 1.52.0 & 1.53.0
  packages/lazarus-shared/package.json
  yarn.lock
Labels: dependencies
